var globCL =
  '<p class="B C">TODO</p> '
+ '<ul><li>alter every project to point to the general files, and make them work with them.'
+ '</li></ul>'
+ 'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/globalscripts/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">5th April  2020</p> '
+ '<ul><li>' + zBug + 'I noticed that the popups were incorrectly placed. No idea why and cannot find where it was changed.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">4th April  2020</p> '
+ '<ul><li>' + zNew + 'initial support for <q>pure</q> css centered and scaled webapps!'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd December 2019</p> '
+ '<ul><li>' + zImp + 'Small tweak to settings UI'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">9th September 2019</p> '
+ '<ul><li>' + zNew + 'added option (always on at the moment) to check for updates on each loading of the app.'
+ '</li><li>' + zBug + 'a couple of bigfixes relating to tooltip code changes preventing scrolling.'
+ '</li><li>' + zBug + 'links should work once more in settings, and also open in a new window.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">8th September 2019</p> '
+ '<ul><li>' + zImp + 'moved all of the rest of the tooltips to it&apos;s own module.'
+ '</li><li>' + zBug + 'adding stuff to the innerhtml of body after modifying elements that were added to the innerhtml reverts the modifications of the initial elelements. tooltips are new elements appended to the body to work around this chrome browser bug.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">5th September 2019</p> '
+ '<ul><li>' + zNew + 'tweaks and bugfixes for the new manual updating code.'
+ '</li><li>' + zBug + 'fixed a couple buttons that had onclick - they don&apos;t work on touchscreens..lol'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">4th September 2019</p> '
+ '<ul><li>' + zNew + 'webapps didn&apos;t seem to update the globalfiles serviceWorker in 2 days, so updating should now be great with being able to manually check for an update (settings > app changeLog) if the serviceWorkers are active, and also toast popups letting you know the progress of any popups, along with a restart button to start using the updated version stright away :D I hope to make updating the food list on it&apos;s own sometime once the project has matured, but still lot&apos;s to do yet!'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">22nd November 2018</p> '
+ '<ul><li>' + zDev + 'global scripts now handles the scrolling.'
+ '</li><li>' + zImp + 'scrolling code improved while I moved it over.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">27th May 2017</p> '
+ '<ul><li>' + zDev + 'a little fooling about with the global volume for individual apps.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">15th April 2017</p> '
+ '<ul><li>' + zImp + 'Added new event trigger for when user closes Settings. This should be great for unpausing a game, etc.'
+ '</li><li>' + zImp + 'New version of app resizing, that should be good for portrait AND landscape.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">5th April 2017</p> '
+ '<ul><li>' + zImp + 'tweaked the tip/support buttons.'
+ '</li><li>' + zImp + 'Added another var to the slider events, so that the initial setting of sliders does not trigger app saving.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd April 2017</p> '
+ '<ul><li>' + zNew + 'Added game keyboard events from memguess, while that project was adapted to use these Global general files.'
+ '</li><li>' + zImp + 'Added another var to the slider events, so that the initial setting of sliders does not trigger app saving.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">28th March 2017</p> '
+ '<ul><li>' + zNew + 'Added input keyboard events and on-screen keyboard dodging from CalorieCalculator, while that project was adapted to use these Global general files.'
+ '</li></ul>'
+ '<hr>' +
+ '<p class="B C">3rd March 2017</p> '
+ '<ul><li>' + zNew + 'Created general files, that should work with all of my apps, and put it on GitHub.'
+ '</li></ul>'
+ '<hr>'
+ 'Earlier development done on every project on here, then before that the Webtop.'
;
