var imgDummy = ' src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACAQMAAABIeJ9nAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjAAIAAAQAASDSLW8AAAAASUVORK5CYII="'
  , baseIP = 'https://stewved.github.io/'
  , gs = baseIP + 'globalscripts/'//for general stuff, like images and scripts.
  , imgSocs = 'style="background:center/contain no-repeat url(\'' + gs + 'images/'

  , appAbout =
  '<hr style=clear:both>'
  + '<img alt="The Author" src="' + gs + 'images/StewVed.jpg" style="'
  + 'float:left;border-radius:0.7em;width:6em;margin:0 .5em .5em 0;">'
  + '<p style="text-align:justify;">'
    + 'Stewart Robinson (StewVed) is creating useful, fun, and educational '
    + 'web (HTML5) applications, that are Free Open Source Software.'
  + '</p>'

 ,  appAboutEx =
  '<p style="text-align:justify;">'
    + 'He has been coding since he was about 7 years old, though back '
    + 'then it was on a Sinclair ZX Spectrum (48k rubber keyboard) '
    + 'using BASIC code.'
  + '</p>'
  + '<p style="text-align:justify;">'
    + 'Years later, he fooled with VB.NET, and C#.NET as the .NET '
    + 'platform was supposed to be OS agnostic, though then he realised '
    + 'that the truly universal choice was the internet since every '
    + 'device has a browser, regardless of the OS it uses.'
  + '</p>'
  + '<p style="text-align:justify;">'
    + 'So, somewhere around 2010, he began learning internet developing '
    + 'from the internet, and has been creating applications for the '
    + 'web ever since!'
  + '</p>'

, supportStewved =
  '<h2 class=B style=margin-bottom:.2em;font-size:1.25em>Free apps with your support!</h2>'
  + '<hr>'
  + '<div id=BraveBAT>'
  + '<a href="https://brave.com/ste944">'
  + '<img src="' + gs + 'images/brave-bat-partnership.svg" alt="Brave Browser & BAT" width="75%">'
  + '</a>'
  + '<p>Support me for <q>free</q> using BAT '
  + '<p id="BATp">Brave is a Chromium-based (think google chrome) browser that blocks adverts for you, so you have an uncluttered browsing experience.<br><br>'
  + 'The browser then gives BAT to websites that you have visited, depending on how long you\'ve stayed and how many times you have visited.</p>'
  + '<p>You can also <q>tip</q> a website (like this one!) my clicking on the BAT '
  + '<img id="BAT" src="' + gs + 'images/logo-full-color.svg" alt="Basic Attention Token" style="height:0.9em;">'
  + ' icon by the address bar.'
  + '</p>'
  + '<p>'
  + 'Download the Brave browser here:<br>'
  + '<a href="https://brave.com/ste944">'
  + '<img src="' + gs + 'images/brave-logotype-dark.svg" alt="Download Brave Browser" width="50%">'
  + '</a>'
  + '<br>'
  + 'This includes my referrer code to let Brave know that I sent you, and they give me some BAT for you just using the Brave browser <q>minimally</q> for at least 30 days.<br><span style="font-weight:bold;">Thank you!</span>'
  + '</p>'
  + '</div>'
  + '<hr>'
  + '<div id=donations>'
  + '<h2 class=B style=margin-bottom:.2em;font-size:1.25em>Support StewVed through PayPal:</h2>'
    //PayPal Donate Button (modded)
  + '<form class="tipButton uButtonGrey" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">' + '<input type="hidden" name="cmd" value="_s-xclick">' + '<input type="hidden" name="hosted_button_id" value="RJMCJX2TE8E4Y">'
    + '<input type="image" class="imgSocs ubLink" ' + imgSocs + 'PaypalDonate.png\');height:100%;width:100%;display:block;cursor: pointer;" ' + imgDummy + ' name="submit" alt="PayPal – The safer, easier way to pay online.">'
  + '</form>'
  + '</div>'
  + '<br>'



, appBugs =
  '<hr style=clear:both>'
  + '<h1 style=margin-bottom:.2em;font-size:1.25em>'
    + 'StewVed\'s standard notice:'
  + '</h1>'
  + '<p style=text-align:center;color:red;margin-top:0;line-height:1.5em;>'
    + 'Warning: May contain Bugs!<br>'
    + 'Cannot guarantee Bug free!<br>'
    + 'Produced on a system where Buggy products are also made!'
  + '</p>'

;
